name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build Application
      run: go build -o seblak99-app ./cmd/main.go 

    - name: Run Tests
      env:
        PAYMENT_SERVER_KEY: ${{ secrets.PAYMENT_SERVER_KEY }} 
      run: go test -v ./test/...